### ISSUE TITLE
二分法实现（golang）

### ISSUE THREAD

**Issue by Vexth** [Vexth/blog#22]
最近在看算法书，以前只是用过没有正式的看过算法方面的书籍。

**二分法** 最基础的算法之一了

照着算法书上撸的代码，如下：
```golang
func rank(arr []int, key int) int {
	lf, lr, m := 1, len(arr), 0
	if lf > lr {
		return -1
	}
	for {
		m = int(math.Floor(float64((lf + lr) / 2)))
		if key < arr[m] {
			lr = m - 1
		} else if key > arr[m] {
			lf = m + 1
		} else {
			break
		}
	}
	return m
}
```
跑一下试试看咯
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 1)) // 1
```
一切正常没有问题！！！以为搞定咯吗？
再试试看把参数`1`改成`17`，跑一下看看咯
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 17))
```
```golang
panic: runtime error: index out of range

goroutine 1 [running]:
main.rank(0xc04205fec8, 0x11, 0x11, 0x11, 0x3206a8)
        E:/GOPATH/src/github.com/dome/dome3/main.go:63 +0xd8
main.main()
        E:/GOPATH/src/github.com/dome/dome3/main.go:118 +0x8a
exit status 2
```
额...报错咯。为什么呢？代码有问题咯，没有考虑到数组以外的因数咯，重写代码试试看咯
```golang
func rank(arr []int, key int) int {
	lf, lr := 0, len(arr)-1
	for lf <= lr {
		// m := lf + (lr - lf) / 2
		// m := (lf + lr) >> 1
		m := int(math.Floor(float64((lf + lr) / 2)))
		mv := arr[m]
		if mv == key {
			return m
		} else if mv > key {
			lr = m - 1
		} else if mv < key {
			lf = m + 1
		}
	}

	return -1
}
```
继续测试吧
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 1)) // 1
fmt.Println(rank(arr, 17)) // -1
```
哦噢，一切正常搞定:star2::honeybee::mouse:

**Comment by Vexth** [comment]
> 最近在看算法书，以前只是用过没有正式的看过算法方面的书籍。
> 
> **二分法** 最基础的算法之一了
> 
> 照着算法书上撸的代码，如下：
> 
> ```go
> func rank(arr []int, key int) int {
> 	lf, lr, m := 1, len(arr), 0
> 	if lf > lr {
> 		return -1
> 	}
> 	for {
> 		m = int(math.Floor(float64((lf + lr) / 2)))
> 		if key < arr[m] {
> 			lr = m - 1
> 		} else if key > arr[m] {
> 			lf = m + 1
> 		} else {
> 			break
> 		}
> 	}
> 	return m
> }
> ```
> 
> 跑一下试试看咯
> 
> ```go
> arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
> fmt.Println(rank(arr, 1)) // 1
> ```
> 
> 一切正常没有问题！！！以为搞定咯吗？
> 再试试看把参数`1`改成`17`，跑一下看看咯
> 
> ```go
> arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
> fmt.Println(rank(arr, 17))
> ```
> 
> ```go
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> main.rank(0xc04205fec8, 0x11, 0x11, 0x11, 0x3206a8)
>         E:/GOPATH/src/github.com/dome/dome3/main.go:63 +0xd8
> main.main()
>         E:/GOPATH/src/github.com/dome/dome3/main.go:118 +0x8a
> exit status 2
> ```
> 
> 额...报错咯。为什么呢？代码有问题咯，没有考虑到数组以为的因数咯，重写代码试试看咯
> 
> ```go
> func rank(arr []int, key int) int {
> 	lf, lr := 0, len(arr)-1
> 	for lf <= lr {
> 		// m := lf + (lr - lf) / 2
> 		// m := (lf + lr) >> 1
> 		m := int(math.Floor(float64((lf + lr) / 2)))
> 		mv := arr[m]
> 		if mv == key {
> 			return m
> 		} else if mv > key {
> 			lr = m - 1
> 		} else if mv < key {
> 			lf = m + 1
> 		}
> 	}
> 
> 	return -1
> }
> ```
> 
> 继续测试吧
> 
> ```go
> arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
> fmt.Println(rank(arr, 1)) // 1
> fmt.Println(rank(arr, 17)) // -1
> ```
> 
> 哦噢，一切正常搞定
