### ISSUE TITLE
二分法（golang）

### ISSUE THREAD

**Issue by Vexth** [Vexth/blog#23]
最近在看算法书，以前只是用过没有正式的看过算法方面的书籍。

**二分法** 最基础的算法之一了

照着算法书上撸的代码，如下：
```golang
func rank(arr []int, key int) int {
	lf, lr, m := 1, len(arr), 0
	if lf > lr {
		return -1
	}
	for {
		m = int(math.Floor(float64((lf + lr) / 2)))
		if key < arr[m] {
			lr = m - 1
		} else if key > arr[m] {
			lf = m + 1
		} else {
			break
		}
	}
	return m
}
```
跑一下试试看咯
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 1)) // 1
```
一切正常没有问题！！！以为搞定咯吗？
再试试看把参数`1`改成`17`，跑一下看看咯
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 17))
```
```golang
panic: runtime error: index out of range

goroutine 1 [running]:
main.rank(0xc04205fec8, 0x11, 0x11, 0x11, 0x3206a8)
        E:/GOPATH/src/github.com/dome/dome3/main.go:63 +0xd8
main.main()
        E:/GOPATH/src/github.com/dome/dome3/main.go:118 +0x8a
exit status 2
```
额...报错咯。为什么呢？代码有问题咯，没有考虑到数组以为的因数咯，重写代码试试看咯
```golang
func rank(arr []int, key int) int {
	lf, lr := 0, len(arr)-1
	for lf <= lr {
		// m := lf + (lr - lf) / 2
		// m := (lf + lr) >> 1
		m := int(math.Floor(float64((lf + lr) / 2)))
		mv := arr[m]
		if mv == key {
			return m
		} else if mv > key {
			lr = m - 1
		} else if mv < key {
			lf = m + 1
		}
	}

	return -1
}
```
继续测试吧
```golang
arr := []int{0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
fmt.Println(rank(arr, 1)) // 1
fmt.Println(rank(arr, 17)) // -1
```
哦噢，一切正常搞定:star2::honeybee::mouse:

**Comment by Vexth** [comment]
avSX||https://api.github.com/repos/

**Comment by Vexth** [comment]
jTIG||https://short-psi.vercel.app/

**Comment by Vexth** [comment]
NmHe||https://www.aliyun.com/?utm_content=se_1008364713&spm=5176.12901015.0.i12901015.4b2e525cOmYqDu

**Comment by Vexth** [comment]
8Tqc||https://translate.google.cn/?sl=auto&tl=zh-CN&text=Logon%20failed%2C%20use%20ctrl%2Bc%20to%20cancel%20basic%20credential%20prompt.&op=translate

**Comment by Vexth** [comment]
sWZs||https://www.baidu.com/s?ie=utf-8&f=8&rsv_bp=1&rsv_idx=1&tn=baidu&wd=%E6%96%B0%E6%B5%AA%E9%82%AE%E7%AE%B1&fenlei=256&oq=vercel&rsv_pq=9ced350800000ab1&rsv_t=253dSxhJ2fUI4jdIGdiSlwo7m5hN%2BaHkWZfJMJOF7QcG0eWvv0ADpZlTiLY&rqlang=cn&rsv_enter=0&rsv_dl=tb&rsv_btype=t&inputT=2643&rsv_sug3=36&rsv_sug1=24&rsv_sug7=101&bs=vercel

**Comment by Vexth** [comment]
TJTz||https://short-psi.vercel.app

**Comment by Vexth** [comment]
RO5e||https://translate.google.cn/?sl=auto&tl=en&text=%E7%9F%AD%E5%9F%9F%E5%90%8D%E6%9C%8D%E5%8A%A1&op=translate
